### ISSUE TITLE
can i use signle UR arm to do the task?

### ISSUE THREAD

**Issue by yanrihong** [VoxAct-B/voxactb#1]
can i use signle UR arm to do the task?

**Comment by arthur801031** [comment]
The bimanual manipulation tasks are designed for use with two robot arms, so they cannot be directly substituted with a single robot arm. You would need to modify the task’s success criteria and waypoints to accommodate this change. If you’re interested in single-arm manipulation, I recommend exploring [PerAct](https://peract.github.io/).

**Comment by Bailey-24** [comment]
What is the main difference between your work and PerAct2: Benchmarking and Learning for Robotic Bimanual Manipulation Tasks.

**Comment by Cheng909865905** [comment]
@yanrihong  Hi, did you realize it? I'm also doing related UR5 real experiments
