### ISSUE TITLE
Request for Partial Real Machine Dataset Release

### ISSUE THREAD

**Issue by yanrihong** [VoxAct-B/voxactb#2]
Dear VoxAct-B Team, I've benefited from your open-sourced simulation dataset. Would it be possible to open-source a part of the real machine dataset for reference? It would be greatly helpful for further research. Thanks!

**Comment by arthur801031** [comment]
Hello,

This is the Open Jar dataset used in our real-world experiment.: https://drive.google.com/file/d/1zU_O-tf9AUbyWHa5RI79YqOlCeoGav_j/view?usp=drive_link

Training scripts:
```
peract/scripts/train_open_jar_ours_vlm_real_robot_v4_acting.sh
peract/scripts/train_open_jar_ours_vlm_real_robot_v4_stabilizing.sh
```

Evaluation script:
```
peract/scripts/eval_open_jar_ours_vlm_real_robot_v4.sh
```

**Comment by yanrihong** [comment]
I am extremely interested in the real machine dataset you provided. Firstly, I would like to know if the collection of this real dataset involved teleoperation. Secondly, if teleoperation was used, what is the model of the teleoperation equipment?
Thank you very much for your time and I look forward to your response.

**Comment by arthur801031** [comment]
1. Yes.
2. [GELLO teleoperation framework](https://wuphilipp.github.io/gello_site/).

Please refer to [Appendix.B for real-world experimental details](https://openreview.net/pdf?id=CPQW5kc0pe).
